// AUTOMATICALLY GENERATED FILE
// SEE scripts/gen_TelnetCommands_h
#ifndef __TELNET_COMMANDS_H
#define __TELNET_COMMANDS_H
string telnetCommandAsStr( unsigned char c );

enum TelnetComands{
	TELNET_COMMAND_SE = 240,
	TELNET_COMMAND_NOP = 241,
	TELNET_COMMAND_DM = 242,
	TELNET_COMMAND_BRK = 243,
	TELNET_COMMAND_IP = 244,
	TELNET_COMMAND_AO = 245,
	TELNET_COMMAND_AYT = 26,
	TELNET_COMMAND_EOF = 236,
	TELNET_COMMAND_SUSP = 237,
	TELNET_COMMAND_ABORT = 238,
	TELNET_COMMAND_EC = 247,
	TELNET_COMMAND_EL = 248,
	TELNET_COMMAND_GA = 249,
	TELNET_COMMAND_SB = 250,
	TELNET_COMMAND_WILL = 251,
	TELNET_COMMAND_WONT = 252,
	TELNET_COMMAND_DO = 253,
	TELNET_COMMAND_DONT = 254,
	TELNET_COMMAND_IAC = 255,
};
#endif

