// AUTOGENERATED FILE
#include <iostream>
#include <map>
#include <sstream>
#include <string>
using namespace std;

#include "TelnetOptions.h"

string telnetOptionAsStr( unsigned char c ) {
	map<unsigned char,string> strmap;
	strmap.insert( pair<unsigned char,string>(0,"TELNET_OPTION_BINARY_TRANS") );
	strmap.insert( pair<unsigned char,string>(1,"TELNET_OPTION_ECHO") );
	strmap.insert( pair<unsigned char,string>(2,"TELNET_OPTION_RECONNECTION") );
	strmap.insert( pair<unsigned char,string>(3,"TELNET_OPTION_SGA") );
	strmap.insert( pair<unsigned char,string>(4,"TELNET_OPTION_MSG_SIZE_NEG") );
	strmap.insert( pair<unsigned char,string>(5,"TELNET_OPTION_STATUS") );
	strmap.insert( pair<unsigned char,string>(6,"TELNET_OPTION_TIMING_MARK") );
	strmap.insert( pair<unsigned char,string>(7,"TELNET_OPTION_REMOTE_TRANS_ECHO") );
	strmap.insert( pair<unsigned char,string>(8,"TELNET_OPTION_OUT_LINE_WIDTH") );
	strmap.insert( pair<unsigned char,string>(9,"TELNET_OPTION_OUT_PAGE_SIZE") );
	strmap.insert( pair<unsigned char,string>(10,"TELNET_OPTION_OUT_CR_DISP") );
	strmap.insert( pair<unsigned char,string>(11,"TELNET_OPTION_OUT_HT_STOPS") );
	strmap.insert( pair<unsigned char,string>(12,"TELNET_OPTION_OUT_HT_DISP") );
	strmap.insert( pair<unsigned char,string>(13,"TELNET_OPTION_OUT_FF_DISP") );
	strmap.insert( pair<unsigned char,string>(14,"TELNET_OPTION_OUT_VT_TS") );
	strmap.insert( pair<unsigned char,string>(15,"TELNET_OPTION_OUT_VT_DISP") );
	strmap.insert( pair<unsigned char,string>(16,"TELNET_OPTION_OUT_LF_DISP") );
	strmap.insert( pair<unsigned char,string>(17,"TELNET_OPTION_EXT_ASCII") );
	strmap.insert( pair<unsigned char,string>(18,"TELNET_OPTION_LOGOUT") );
	strmap.insert( pair<unsigned char,string>(19,"TELNET_OPTION_BYTE_MACRO") );
	strmap.insert( pair<unsigned char,string>(20,"TELNET_OPTION_DATA_ENTRY_TERM") );
	strmap.insert( pair<unsigned char,string>(21,"TELNET_OPTION_SUDDUP") );
	strmap.insert( pair<unsigned char,string>(22,"TELNET_OPTION_SUDDUP_OUTPUT") );
	strmap.insert( pair<unsigned char,string>(23,"TELNET_OPTION_SEND_LOCATION") );
	strmap.insert( pair<unsigned char,string>(24,"TELNET_OPTION_TERM_TYPE") );
	strmap.insert( pair<unsigned char,string>(25,"TELNET_OPTION_EOR") );
	strmap.insert( pair<unsigned char,string>(26,"TELNET_OPTION_TACACS") );
	strmap.insert( pair<unsigned char,string>(27,"TELNET_OPTION_OUTPUT_MARKING") );
	strmap.insert( pair<unsigned char,string>(28,"TELNET_OPTION_TERM_LOCATION_NUM") );
	strmap.insert( pair<unsigned char,string>(29,"TELNET_OPTION_3270_REGIME") );
	strmap.insert( pair<unsigned char,string>(30,"TELNET_OPTION_X_DOT_3_PAD") );
	strmap.insert( pair<unsigned char,string>(31,"TELNET_OPTION_NEG_WINDOW_SIZE") );
	strmap.insert( pair<unsigned char,string>(32,"TELNET_OPTION_TERM_SPEED") );
	strmap.insert( pair<unsigned char,string>(33,"TELNET_OPTION_REMOTE_FLOW_CONTROL") );
	strmap.insert( pair<unsigned char,string>(34,"TELNET_OPTION_LINEMODE") );
	strmap.insert( pair<unsigned char,string>(35,"TELNET_OPTION_X_DISP_LOCATION") );
	strmap.insert( pair<unsigned char,string>(36,"TELNET_OPTION_ENV") );
	strmap.insert( pair<unsigned char,string>(37,"TELNET_OPTION_AUTH") );
	strmap.insert( pair<unsigned char,string>(38,"TELNET_OPTION_ENCRYPT") );
	strmap.insert( pair<unsigned char,string>(39,"TELNET_OPTION_NEW_ENV") );
	strmap.insert( pair<unsigned char,string>(40,"TELNET_OPTION_TN3270E") );
	strmap.insert( pair<unsigned char,string>(41,"TELNET_OPTION_XAUTH") );
	strmap.insert( pair<unsigned char,string>(42,"TELNET_OPTION_CHARSET") );
	strmap.insert( pair<unsigned char,string>(43,"TELNET_OPTION_RSP") );
	strmap.insert( pair<unsigned char,string>(44,"TELNET_OPTION_COMPORT_CONTROL") );
	strmap.insert( pair<unsigned char,string>(45,"TELNET_OPTION_SUPRESS_LOCAL_ECHO") );
	strmap.insert( pair<unsigned char,string>(46,"TELNET_OPTION_START_TLS") );
	strmap.insert( pair<unsigned char,string>(47,"TELNET_OPTION_KERMIT") );
	strmap.insert( pair<unsigned char,string>(48,"TELNET_OPTION_SENDURL") );
	strmap.insert( pair<unsigned char,string>(49,"TELNET_OPTION_FORWARD_X") );
	strmap.insert( pair<unsigned char,string>(50,"TELNET_OPTION_UNASSIGNED") );
	strmap.insert( pair<unsigned char,string>(51,"TELNET_OPTION_PRAGMA_LOGON") );
	strmap.insert( pair<unsigned char,string>(52,"TELNET_OPTION_SSPI_LOGIN") );
	strmap.insert( pair<unsigned char,string>(53,"TELNET_OPTION_PRAGMA_HEARTBEAT") );
	strmap.insert( pair<unsigned char,string>(54,"TELNET_OPTION_EXTENDED") );

	if( strmap.find(c) != strmap.end() ) {
		return strmap[c];
	} else {
		stringstream ss;
		ss << (int)c;
		string s;
		ss >> s;
		return s;
	}
}

